-- 코드를 입력하세요
SELECT EMPLOYEE_ID, sum_price AS '매출액' FROM 
(
SELECT EMPLOYEE_ID, COUNT(EMPLOYEE_ID) AS count_selling, SUM(PRICE) AS sum_price FROM SELLINGS GROUP BY EMPLOYEE_ID
)res1
WHERE count_selling = (SELECT COUNT(EMPLOYEE_ID) AS temp FROM SELLINGS GROUP BY EMPLOYEE_ID ORDER BY temp DESC LIMIT 1)
ORDER BY sum_price DESC 
LIMIT 1
